### ISSUE TITLE
Feature: Object Detection with Voice Announcement

### ISSUE THREAD

**Issue by Wahyudi-Changra** [Wahyudi-Changra/Object-Detection#8]
**Description**:
Add a function that detects objects in a video stream and announces them via voice. 

**Requirements**:
1. Detect objects using YOLOv8 and display bounding boxes.
2. Announce each object detected with a voice message using pyttsx3.
3. Ensure that the same object is only announced once within a certain interval to avoid repetition.

**Resources**:
- [YOLOv8 Documentation](https://docs.ultralytics.com/)
- [OpenCV Python Documentation](https://docs.opencv.org/)
- [pyttsx3 Documentation](https://pyttsx3.readthedocs.io/)

**Comment by DThanh2306** [comment]
Hello, can you assign me

**Comment by Wahyudi-Changra** [comment]
Thanks for your help
